name: release

on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
        - name: checkout
          id: checkout_code
          uses: actions/checkout@v4

        - name: setup_msbuild
          id: setup_msbuild
          uses: microsoft/setup-msbuild@v2
                
        - name: run_msbuild
          id: run_msbuild
          run: |
            echo ${{ github.sha }} > Release.txt
            msbuild .\gitactionstest_dotnet8.sln -t:clean /p:Configuration=Release
            nuget restore .\gitactionstest_dotnet8.sln
            msbuild .\gitactionstest_dotnet8.sln -t:build /p:Configuration=Release
            msbuild .\gitactionstest_dotnet8.sln -t:publish /p:Configuration=Release
            git archive --format=zip --output=./gitactionstest_dotnet8.zip ./bin/Release/net8.0/publish

        - name: result
          id: result
          run: |
            dir /s /b bin

        - name: release
          uses: softprops/action-gh-release@v2
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: |
              Release.txt
              gitactionstest_dotnet8.zip

