name: release

on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
        - name: checkout
          id: checkout_code
          uses: actions/checkout@v4

        - name: setup_msbuild
          id: setup_msbuild
          uses: microsoft/setup-msbuild@v2
                
        - name: run_msbuild
          id: run_msbuild
          run: |
            echo ${{ github.sha }} > Release.txt
            msbuild .\gitactionstest_dotnet8.sln -t:clean,build,publish -restore /p:Configuration=Release
            
        - shell: cmd
          id: cmd
          run: |
            7z a gitactionstest_dotnet8.zip .\bin\Release\net8.0\publish\*
            dir /s /b 

        - name: release
          uses: softprops/action-gh-release@v2
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: |
              Release.txt
              gitactionstest_dotnet8.zip

